version: '3.1'

services:

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpwd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpwd
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpwd@mongo:27017/

volumes:
  mongodata: